from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
OUTPUT = ROOT / "output" / "History" / "World-War-I"


def q(number, label, points, source, nl, en, answer_nl, answer_en):
    return {"number": number, "label": label, "points": points, "source": source, "nl": nl, "en": en, "answer_nl": answer_nl, "answer_en": answer_en}


PASS = [
    q(1, "R", 2, "§1.2 Causes of the war", "Noem de twee groepen die in de Eerste Wereldoorlog tegen elkaar vochten.", "Name the two groups that fought each other in World War I.", "De Geallieerden en de Centralen.", "The Allies and the Central Powers."),
    q(2, "R", 2, "§1.2 Causes of the war", "Wat is militarisme?", "What is militarism?", "Het hoog waarderen van militaire waarden en het verheerlijken van het leger.", "Placing high value on military values and glorifying the army."),
    q(3, "R", 2, "§1.2 A quick start", "Wat gebeurde er op 28 juni 1914 in Sarajevo?", "What happened in Sarajevo on 28 June 1914?", "De Oostenrijkse kroonprins Franz Ferdinand werd vermoord.", "The Austrian crown prince Franz Ferdinand was assassinated."),
    q(4, "R", 2, "§1.2 Fight at the western front", "Wat waren loopgraven?", "What were trenches?", "Diep uitgegraven gangen, versterkt met zandzakken en prikkeldraad.", "Deeply dug hallways reinforced with sandbags and barbed wire."),
    q(5, "R", 2, "§1.3 The Russian empire", "Noem twee zwakke punten van het Russische rijk in 1914.", "Name two weaknesses of the Russian empire in 1914.", "De industrialisatie was nauwelijks begonnen en veel boeren waren arm, ongeletterd en hadden weinig rechten. Ook had de tsaar absolute macht.", "Industrialisation had barely started and many farmers were poor, illiterate and had few rights. The tsar also had absolute power."),
    q(6, "R", 2, "§1.3 The Russian empire", "Wat was de Doema?", "What was the Duma?", "Het parlement dat de tsaar na de opstanden van 1905 aarzelend instelde, maar dat weinig echte macht kreeg.", "The parliament the tsar reluctantly appointed after the 1905 revolts, but which received little real power."),
    q(7, "R", 2, "§1.3 Russia becomes a republic", "Waarom ontstond er in 1917 hongersnood in de Russische steden?", "Why did famine arise in Russian cities in 1917?", "Er kwam tegen het einde van 1916 onvoldoende voedsel naar de steden.", "By the end of 1916, not enough food was reaching the cities."),
    q(8, "R", 2, "§1.3 Communist Russia", "Wie waren de bolsjewieken?", "Who were the Bolsheviks?", "De radicale socialisten rond Lenin; de naam betekende in het Russisch ongeveer 'meerderheid'.", "The radical socialists around Lenin; the name meant roughly 'majority' in Russian."),
    q(9, "R", 2, "§1.4 The Peace of Versailles", "Wanneer en waar begon de vredesconferentie na de Eerste Wereldoorlog?", "When and where did the peace conference after World War I begin?", "In Parijs, in januari 1919.", "In Paris, in January 1919."),
    q(10, "R", 2, "§1.4 The influence of nationalism", "Wat betekent het recht op zelfbeschikking?", "What does the right to self-determination mean?", "Het recht van volken om hun eigen levenswijze en regering te kiezen.", "The right of peoples to choose their own way of life and government."),
    q(11, "R", 2, "§1.4 The formation of Turkey", "Wie werd de eerste president van de republiek Turkije?", "Who became the first president of the Republic of Turkey?", "Mustafa Kemal, later Ataturk genoemd.", "Mustafa Kemal, later called Ataturk."),
    q(12, "R", 2, "§1.5 Consequences of the neutrality", "Waarom bleef Nederland tijdens de Eerste Wereldoorlog neutraal?", "Why did the Netherlands remain neutral during World War I?", "Nederland wilde niet aan de oorlog deelnemen en koos een onpartijdige positie.", "The Netherlands did not want to participate in the war and chose an impartial position."),
    q(13, "T1", 2, "§1.2 Fight at the eastern front", "Wat gebeurde er begin 1918 aan het Oostfront?", "What happened on the Eastern Front in early 1918?", "Rusland sloot vrede met Duitsland en stond grote delen van Zuid-Rusland en Oekraiene af.", "Russia made peace with Germany and gave large parts of southern Russia and Ukraine to Germany."),
    q(14, "T1", 2, "§1.3 Russia becomes a republic", "Leg uit waarom de Februarirevolutie Rusland tot een republiek maakte.", "Explain why the February Revolution turned Russia into a republic.", "Soldaten muitten en sloten zich aan bij demonstranten. Nicolaas II trad af en de Doema vormde de regering.", "Soldiers mutinied and joined the protesters. Nicholas II stepped down and the Duma formed the government."),
    q(15, "T1", 2, "§1.3 Communist Russia", "Wat gebeurde er tijdens de Oktoberrevolutie?", "What happened during the October Revolution?", "Gewapende communisten bezetten belangrijke gebouwen in Sint-Petersburg en namen de regering over.", "Armed communists occupied important buildings in Saint Petersburg and captured the government."),
    q(16, "T1", 2, "§1.4 The formation of Turkey", "Wat was etnische zuivering?", "What was ethnic cleansing?", "Handelingen om een etnische groep in een gebied kleiner te maken, bijvoorbeeld door mensen te vermoorden of te verdrijven.", "Actions to reduce an ethnic group in a region, for example by murdering or expelling people."),
    q(17, "T1", 2, "§1.5 Consequences of the neutrality", "Noem twee gevolgen van de neutraliteit voor Nederland.", "Name two consequences of neutrality for the Netherlands.", "Nederland hield 200.000 soldaten paraat en ving veel Belgische vluchtelingen op. Ook werden handel en goederen schaarser.", "The Netherlands kept 200,000 soldiers ready and received many Belgian refugees. Trade was also affected and goods became scarcer."),
    q(18, "T1", 2, "§1.4 New ethnic tension", "Waarom veroorzaakte de nieuwe kaart van Europa na 1919 nieuwe spanningen?", "Why did the new map of Europe create new tensions after 1919?", "Nieuwe staten bevatten etnische minderheden en zelfbeschikking werd niet overal toegepast.", "New states contained ethnic minorities and self-determination was not applied everywhere."),
    q(19, "T2", 2, "§1.2 and §1.3", "Leg uit hoe de oorlog bijdroeg aan de val van de Russische tsaar.", "Explain how the war contributed to the fall of the Russian tsar.", "De oorlog veroorzaakte voedseltekorten en hongersnood. Daardoor ontstonden stakingen en protesten; soldaten weigerden de orde te herstellen en de tsaar trad af.", "The war caused food shortages and famine. This led to strikes and protests; soldiers refused to restore order and the tsar stepped down."),
    q(20, "T2", 2, "§1.4 and §1.5", "Geef een voorbeeld waaruit blijkt dat de oorlog ook gevolgen had voor landen die niet meevochten.", "Give one example showing that the war also affected countries that did not fight.", "Nederland bleef neutraal, maar mobiliseerde, ving Belgische vluchtelingen op en kreeg te maken met schaarste en veranderingen in de handel.", "The Netherlands remained neutral but mobilised, received Belgian refugees and faced shortages and changes in trade."),
]

EXCELLENT = [
    q(1, "R", 2, "§1.3 The Russian empire", "Waarom was het Russische rijk in 1914 tegelijk sterk en zwak?", "Why was the Russian empire both strong and weak in 1914?", "Het was groot, had veel inwoners en grondstoffen, maar was nauwelijks geindustrialiseerd; veel boeren waren arm en hadden weinig rechten.", "It was large and had many inhabitants and resources, but was barely industrialised; many farmers were poor and had few rights."),
    q(2, "T1", 3, "§1.2 Causes of the war", "Leg uit hoe nationalisme, militarisme en de wapenwedloop de oorlogsdreiging vergrootten.", "Explain how nationalism, militarism and the arms race increased the threat of war.", "Nationalisme zorgde voor rivaliteit tussen volken. Militarisme verheerlijkte het leger. Daardoor bouwden landen steeds meer en sterkere wapens op, waardoor een conflict sneller kon escaleren.", "Nationalism created rivalry between peoples. Militarism glorified the army. Countries therefore built up more and stronger weapons, making escalation easier."),
    q(3, "T1", 3, "§1.2 A quick start", "Beschrijf de keten van gebeurtenissen tussen de moord in Sarajevo en de Britse oorlogsverklaring aan Duitsland.", "Describe the chain of events between the Sarajevo assassination and Britain's declaration of war on Germany.", "Oostenrijk verklaarde Servie de oorlog; Rusland steunde Servie; Duitsland verklaarde Rusland en daarna Frankrijk de oorlog; Duitsland viel het neutrale Belgie binnen; Groot-Brittannie verklaarde daarop Duitsland de oorlog.", "Austria declared war on Serbia; Russia supported Serbia; Germany declared war on Russia and then France; Germany invaded neutral Belgium; Britain then declared war on Germany."),
    q(4, "T1", 3, "§1.3 Russia becomes a republic", "Vergelijk de Februarirevolutie en de Oktoberrevolutie.", "Compare the February Revolution and the October Revolution.", "De Februarirevolutie was een democratische revolutie waarbij de tsaar aftrad en de Doema regeerde. De Oktoberrevolutie was een communistische machtsovername waarbij Lenin en de bolsjewieken de regering veroverden.", "The February Revolution was a democratic revolution in which the tsar stepped down and the Duma governed. The October Revolution was a communist seizure of power in which Lenin and the Bolsheviks captured the government."),
    q(5, "T1", 3, "§1.3 Communist Russia", "Noem drie kenmerken van de communistische staat onder Lenin.", "Name three characteristics of the communist state under Lenin.", "Een eenpartijstaat, afschaffing van politieke tegenstanders, terreur en geheime dienst Cheka/KGB, concentratiekampen en een sterke bureaucratie zijn goede voorbeelden.", "A one-party state, suppression of political opponents, terror and the secret service Cheka/KGB, concentration camps and a large bureaucracy are valid examples."),
    q(6, "T2", 3, "§1.4 The Peace of Versailles", "Leg uit waarom het Verdrag van Versailles voor Duitsland vernederend en zwaar was.", "Explain why the Treaty of Versailles was humiliating and harsh for Germany.", "Duitsland moest de oorlogsschuld aanvaarden, herstelbetalingen doen, gebied en kolonies afstaan, zware wapens inleveren en het leger beperken tot 100.000 soldaten. Duitsland mocht niet mee beslissen.", "Germany had to accept responsibility, pay reparations, lose territory and colonies, surrender heavy weapons and limit its army to 100,000 soldiers. Germany was excluded from the decisions."),
    q(7, "T2", 3, "§1.4 The influence of nationalism", "Leg uit hoe nationalisme zowel nieuwe staten als nieuwe problemen veroorzaakte.", "Explain how nationalism caused both new states and new problems.", "Volken vormden nieuwe staten zoals Polen en Tsjechoslowakije. Maar grenzen plaatsten ook minderheden in andere staten, bijvoorbeeld Duitstaligen in Tsjechoslowakije, waardoor nieuwe spanningen ontstonden.", "Peoples formed new states such as Poland and Czechoslovakia. But borders also placed minorities in other states, such as German speakers in Czechoslovakia, creating new tensions."),
    q(8, "T2", 3, "§1.4 The formation of Turkey", "Leg uit hoe Mustafa Kemal de republiek Turkije vormde.", "Explain how Mustafa Kemal formed the Republic of Turkey.", "Turkse nationalisten verzetten zich tegen het verdrag van 1920. Kemal vormde in Ankara een parlement en leger, verdreef de Grieken uit Anatolie, zette de sultan af en riep in 1923 de republiek uit.", "Turkish nationalists rejected the 1920 treaty. Kemal formed a parliament and army in Ankara, drove the Greeks out of Anatolia, deposed the sultan and declared the republic in 1923."),
    q(9, "T2", 3, "§1.5 Consequences of the neutrality", "Leg uit waarom neutraliteit Nederland niet buiten de gevolgen van de oorlog hield.", "Explain why neutrality did not keep the Netherlands outside the consequences of the war.", "Nederland moest mobiliseren en 200.000 soldaten paraat houden, ving meer dan een miljoen Belgische vluchtelingen op en kreeg schaarste, duurdere producten en problemen met invoer en uitvoer.", "The Netherlands had to mobilise and keep 200,000 soldiers ready, received over a million Belgian refugees and faced shortages, higher prices and problems with imports and exports."),
    q(10, "T2", 3, "§1.2 and §1.3", "Leg uit hoe de Eerste Wereldoorlog de politieke machtsverhoudingen in Rusland veranderde.", "Explain how World War I changed political power in Russia.", "De oorlog veroorzaakte voedseltekorten, protesten en muiterij. De tsaar trad af en de Doema vormde de regering. Daarna namen sovjets en uiteindelijk de bolsjewieken de macht over.", "The war caused food shortages, protests and mutiny. The tsar stepped down and the Duma formed the government. Soviets and eventually the Bolsheviks then took power."),
    q(11, "I", 3, "§1.4 and §1.5", "Was de nieuwe kaart van Europa een oplossing of een nieuw probleem? Geef twee argumenten.", "Was the new map of Europe a solution or a new problem? Give two arguments.", "Beide: nieuwe staten gaven sommige volken zelfstandigheid, maar nieuwe grenzen lieten minderheden achter en veroorzaakten etnische spanningen. Ook werd zelfbeschikking niet overal toegepast.", "Both: new states gave some peoples independence, but new borders left minorities behind and caused ethnic tensions. Self-determination was also not applied everywhere."),
    q(12, "I", 3, "§1.2, §1.3 and §1.4", "Leg uit hoe de oorlog, revolutie en vredesverdragen samen de politieke kaart van Europa veranderden.", "Explain how war, revolution and peace treaties together changed Europe's political map.", "De oorlog verzwakte of vernietigde rijken. In Rusland ontstond een communistische staat. Oostenrijk-Hongarije en het Ottomaanse rijk vielen uiteen. Vredesverdragen vormden nieuwe staten en nieuwe grenzen.", "The war weakened or destroyed empires. Russia became a communist state. Austria-Hungary and the Ottoman Empire fell apart. Peace treaties created new states and borders."),
    q(13, "I", 3, "§1.4 and §1.5", "Vergelijk de gevolgen van oorlog voor Duitsland en voor het neutrale Nederland.", "Compare the consequences of the war for Germany and neutral Netherlands.", "Duitsland verloor gebied, kolonies, wapens en macht en moest herstelbetalingen doen. Nederland bleef buiten de strijd, maar mobiliseerde, ving vluchtelingen op en kreeg economische schaarste en duurdere producten.", "Germany lost territory, colonies, weapons and power and had to pay reparations. The Netherlands stayed out of the fighting but mobilised, received refugees and faced shortages and higher prices."),
    q(14, "I", 3, "§1.3 and §1.4", "Beoordeel de stelling: 'Nationalisme bracht na de oorlog meer vrede.' Gebruik twee voorbeelden uit de theorie.", "Assess the statement: 'Nationalism brought more peace after the war.' Use two examples from the theory.", "De stelling is slechts gedeeltelijk juist. Nationalisme hielp bij de vorming van nieuwe staten, maar veroorzaakte ook etnische zuivering, gedwongen volksverhuizingen en spanningen tussen meerderheden en minderheden.", "The statement is only partly correct. Nationalism helped create new states, but also caused ethnic cleansing, forced migration and tensions between majorities and minorities."),
]


def make_markdown(filename, title, questions, answer_key=False, chapter="1.2-1.5"):
    total = sum(item["points"] for item in questions)
    lines = [f"# {title}", "", "| Veld / Field | Details / Details |", "|---|---|", "| Vak / Subject | Geschiedenis / History |", "| Boek / Book | Geschiedeniswerkplaats 3e editie 3VWO English Edition |", f"| Hoofdstuk / Chapter | H1 World War I: {chapter} |", f"| Totaal / Total | {total} punten / points |"]
    if answer_key:
        lines += ["*Dit zijn modelantwoorden. Gelijkwaardige antwoorden die op de theorie zijn gebaseerd zijn goed.*", "", "Model answers are provided. Equivalent answers grounded in the theory are acceptable.", ""]
        for item in questions:
            lines += [f"## {item['number']}. [{item['label']}, {item['points']}p]", f"*{item['nl']}*", "", item["en"], "", f"**Antwoord / Answer - Bron / Source:** {item['source']}", "", f"*{item['answer_nl']}*", "", item["answer_en"], "", f"**Punten / Points:** {item['points']}p beschikbaar / available.", ""]
        lines += ["## Beoordeling / Grading", "Cijfer = 1 + 9 x (behaalde punten / totaal aantal punten), afgerond op één decimaal. / Grade = 1 + 9 x (points scored / total points), rounded to one decimal.", "", "| Punten / Points | Cijfer / Grade | Herhalen / Review |", "|---:|---:|---|"]
        for points in [0, 10, 20, 24, 28, 32, 36, 40]:
            lines.append(f"| {points} | {1 + 9 * points / total:.1f} | §{chapter} |")
    else:
        lines += ["| Tijd / Time | 45 minuten / minutes |", "| Naam / Name | ____________________    Datum / Date: __________ |", "", "*Instructies: Beantwoord elke vraag. Nederlands staat eerst; Engels volgt eronder.*", "", "Instructions: Answer every question. Dutch comes first; English follows below it.", ""]
        for item in questions:
            lines += [f"## {item['number']}. [{item['label']}, {item['points']}p]", f"*{item['nl']}*", "", item["en"], "", "________________________________________________________________________________", ""]
            if item["points"] >= 3:
                lines += ["________________________________________________________________________________", ""]
            lines += ["**Klik om het antwoord te tonen / Click to show the answer:**", "", "<details>", "<summary>Antwoord / Answer</summary>", "", f"**Bron / Source:** {item['source']}", "", f"*{item['answer_nl']}*", "", item["answer_en"], "", f"**Punten / Points:** {item['points']}p beschikbaar / available.", "", "</details>", ""]
        lines += ["## Beoordeling / Grading", "Cijfer = 1 + 9 x (behaalde punten / totaal aantal punten), afgerond op één decimaal. / Grade = 1 + 9 x (points scored / total points), rounded to one decimal.", "", "| Punten / Points | Cijfer / Grade | Herhalen / Review |", "|---:|---:|---|"]
        for points in [0, 10, 20, 24, 28, 32, 36, 40]:
            lines.append(f"| {points} | {1 + 9 * points / total:.1f} | §{chapter} |")
    (OUTPUT / filename).write_text("\n".join(lines) + "\n", encoding="utf-8")


OUTPUT.mkdir(parents=True, exist_ok=True)
make_markdown("History_H1_1.2-1.5_Test-A_Pass.md", "H1 World War I 1.2-1.5 - Test A / Pass level", PASS)
make_markdown("History_H1_1.2-1.5_Test-B_Excellent.md", "H1 World War I 1.2-1.5 - Test B / Excellent level", EXCELLENT)
make_markdown("History_H1_1.2-1.5_Test-A_Pass_AnswerKey.md", "H1 World War I 1.2-1.5 - Test A / Pass level - Answer key", PASS, answer_key=True)
make_markdown("History_H1_1.2-1.5_Test-B_Excellent_AnswerKey.md", "H1 World War I 1.2-1.5 - Test B / Excellent level - Answer key", EXCELLENT, answer_key=True)
print("Created tests and standalone answer keys in", OUTPUT)
